<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="5" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="15243" started-at="2023-07-02T15:54:52 IST" finished-at="2023-07-02T15:55:07 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="15243" started-at="2023-07-02T15:54:52 IST" finished-at="2023-07-02T15:55:07 IST">
      <class name="com.RestAssured.restfulbooker.RestfulBookerE2ETests">
        <test-method status="PASS" signature="createNewBooking()[pri:0, instance:com.RestAssured.restfulbooker.RestfulBookerE2ETests@5f282abb]" name="createNewBooking" duration-ms="8235" started-at="2023-07-02T15:54:52 IST" finished-at="2023-07-02T15:55:01 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewBooking -->
        <test-method status="PASS" signature="createToken()[pri:0, instance:com.RestAssured.restfulbooker.RestfulBookerE2ETests@5f282abb]" name="createToken" duration-ms="1845" started-at="2023-07-02T15:55:01 IST" finished-at="2023-07-02T15:55:02 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createToken -->
        <test-method status="PASS" signature="getBookingData()[pri:0, instance:com.RestAssured.restfulbooker.RestfulBookerE2ETests@5f282abb]" name="getBookingData" duration-ms="2312" started-at="2023-07-02T15:55:02 IST" finished-at="2023-07-02T15:55:05 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getBookingData -->
        <test-method status="FAIL" signature="getBookingDetailsById()[pri:0, instance:com.RestAssured.restfulbooker.RestfulBookerE2ETests@5f282abb]" name="getBookingDetailsById" duration-ms="1356" started-at="2023-07-02T15:55:05 IST" finished-at="2023-07-02T15:55:06 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[{
  "firstname" : "Darby",
  "additionalneeds" : "Breakfast",
  "bookingdates" : {
    "checkin" : "2023-06-14",
    "checkout" : "2023-07-02"
  },
  "totalprice" : 145,
  "depositpaid" : true,
  "lastname" : "Stark"
} expected:<{"firstname":"Darby","lastname":"Stark","totalprice":145,"depositpaid":true,"bookingdates":{"checkin":"2023-06-14","checkout":"2023-07-02"},"additionalneeds":"Breakfast"}> but was:<STRICT_ORDER>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: {
  "firstname" : "Darby",
  "additionalneeds" : "Breakfast",
  "bookingdates" : {
    "checkin" : "2023-06-14",
    "checkout" : "2023-07-02"
  },
  "totalprice" : 145,
  "depositpaid" : true,
  "lastname" : "Stark"
} expected:<{"firstname":"Darby","lastname":"Stark","totalprice":145,"depositpaid":true,"bookingdates":{"checkin":"2023-06-14","checkout":"2023-07-02"},"additionalneeds":"Breakfast"}> but was:<STRICT_ORDER>
at org.testng.AssertJUnit.fail(AssertJUnit.java:47)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:330)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:66)
at com.RestAssured.restfulbooker.RestfulBookerE2ETests.getBookingDetailsById(RestfulBookerE2ETests.java:86)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getBookingDetailsById -->
        <test-method status="PASS" signature="updateBookingDetails()[pri:0, instance:com.RestAssured.restfulbooker.RestfulBookerE2ETests@5f282abb]" name="updateBookingDetails" duration-ms="1381" started-at="2023-07-02T15:55:06 IST" finished-at="2023-07-02T15:55:07 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateBookingDetails -->
      </class> <!-- com.RestAssured.restfulbooker.RestfulBookerE2ETests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
